### ISSUE TITLE
Need an image showing the feedback in action

### ISSUE THREAD

**Issue by shtrom** [redaxmedia/chroma-feedback#23]
The term capture in the README.md doesn't really show what this project does. As a matter of fact, I'm not certain what it does.

It would be good to add a photo/animated GIF of the keyboard, that matches what the terminal capture shows.

**Comment by redaxmedia** [comment]
Hello,

> What is an extreme feedback device?

The idea behind that kind of devices is to make your continuous integration status visible on your desk instead of just getting a notification via email.

There is no out of the box solution available. Geeks usually program a Raspberry PI and connect it to lava lamps or tiny [traffic lights](http://gitgear.com/img/lamp1.jpg) to show everyone in the office that a build recently failed or passed.

> What does Chroma Feedback solve?

This project is using Razer devices, that used to come with a LED backlight, to show the current status of your builds by changing the colors to green, yellow, white or red.

**Comment by shtrom** [comment]
Yeah, that's what I thought. But the README.md would definitely be improved with an image of the code in action on the Razers. Arguably this is a bit of a tongue-in-cheek issue (:

**Comment by redaxmedia** [comment]
I have to record a video to show things in action - you are right!
